@DientesLimpios.API_HostAddress = http://localhost:5221/api/consultorios

GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8KzgGGV9wRVEkndSQLLrKiB5hvQTVIcgT9E0caiZ-MHGOLmDBmVuX0wAzPKcDwgjBquG-uGshwMt4ohWkbRv-27WHfCkjwdJ1rQA_l7eAV64xBgr_J1zrdbUMUu4S8uNradzt3Kns8FqGQXJSZO_fOuVui_xtI5LjI9b8F8iEGbga-6H6fkk507EH6RO0HOLru1UL5bhH8qrrx3_DUbq5XLzRyzLtjq0npFFPEMk6Gqn3Tf1ldq4wF-ewvIIv69WOeD_fZlWnm89DEdMXlLk1ERnccNk_TXXj-5iPub_hIAw1-eyNL4fBBEAJoS965P-cVGQklchl4nwf9kbA3s0u7sDXfK7vGvBtAW33rDKqukG5cKFfrAUh2Ji_Oauy-0nTQsNB-WbJ7WeMpyKfrZDAu_DG4kO--ztDHTHFsPNoENR3b5xi5BXz4sSy5Sba86qXZ-9IsplAP29i1FrlO5Y-jyRf46o1Zh2J3JS9G2kievWbWrr103OgEnvEsEBqszsr0UITeVYUf0q7b9St3L3UODck-_TdhtKBdle_thA_Z0RYB8EYSpN48RP3YRb42_LtAm3NVHsqDxBH4A7pxYfmjGdx0DGg5h6zD2Dts82zrUSkQPRObvArcW3A0T_PmJX-8i67fSBmOI3GJM69Pb7OLCwOz8WoUvw_SQwjoIOj2mZd6-8-9Vy4j4o6bMZmD9AC2dQbHbwezH4adlZ40KyCjUvzvlUKqm51n8vCInGibJd88NiixZeyCdilAud_cmyNw
###
GET {{DientesLimpios.API_HostAddress}}/019D6E3B-888A-742F-BD39-F56EA40A316D
Accept: application/json
Authorization: Bearer CfDJ8KzgGGV9wRVEkndSQLLrKiB5hvQTVIcgT9E0caiZ-MHGOLmDBmVuX0wAzPKcDwgjBquG-uGshwMt4ohWkbRv-27WHfCkjwdJ1rQA_l7eAV64xBgr_J1zrdbUMUu4S8uNradzt3Kns8FqGQXJSZO_fOuVui_xtI5LjI9b8F8iEGbga-6H6fkk507EH6RO0HOLru1UL5bhH8qrrx3_DUbq5XLzRyzLtjq0npFFPEMk6Gqn3Tf1ldq4wF-ewvIIv69WOeD_fZlWnm89DEdMXlLk1ERnccNk_TXXj-5iPub_hIAw1-eyNL4fBBEAJoS965P-cVGQklchl4nwf9kbA3s0u7sDXfK7vGvBtAW33rDKqukG5cKFfrAUh2Ji_Oauy-0nTQsNB-WbJ7WeMpyKfrZDAu_DG4kO--ztDHTHFsPNoENR3b5xi5BXz4sSy5Sba86qXZ-9IsplAP29i1FrlO5Y-jyRf46o1Zh2J3JS9G2kievWbWrr103OgEnvEsEBqszsr0UITeVYUf0q7b9St3L3UODck-_TdhtKBdle_thA_Z0RYB8EYSpN48RP3YRb42_LtAm3NVHsqDxBH4A7pxYfmjGdx0DGg5h6zD2Dts82zrUSkQPRObvArcW3A0T_PmJX-8i67fSBmOI3GJM69Pb7OLCwOz8WoUvw_SQwjoIOj2mZd6-8-9Vy4j4o6bMZmD9AC2dQbHbwezH4adlZ40KyCjUvzvlUKqm51n8vCInGibJd88NiixZeyCdilAud_cmyNw
###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8KzgGGV9wRVEkndSQLLrKiB5hvQTVIcgT9E0caiZ-MHGOLmDBmVuX0wAzPKcDwgjBquG-uGshwMt4ohWkbRv-27WHfCkjwdJ1rQA_l7eAV64xBgr_J1zrdbUMUu4S8uNradzt3Kns8FqGQXJSZO_fOuVui_xtI5LjI9b8F8iEGbga-6H6fkk507EH6RO0HOLru1UL5bhH8qrrx3_DUbq5XLzRyzLtjq0npFFPEMk6Gqn3Tf1ldq4wF-ewvIIv69WOeD_fZlWnm89DEdMXlLk1ERnccNk_TXXj-5iPub_hIAw1-eyNL4fBBEAJoS965P-cVGQklchl4nwf9kbA3s0u7sDXfK7vGvBtAW33rDKqukG5cKFfrAUh2Ji_Oauy-0nTQsNB-WbJ7WeMpyKfrZDAu_DG4kO--ztDHTHFsPNoENR3b5xi5BXz4sSy5Sba86qXZ-9IsplAP29i1FrlO5Y-jyRf46o1Zh2J3JS9G2kievWbWrr103OgEnvEsEBqszsr0UITeVYUf0q7b9St3L3UODck-_TdhtKBdle_thA_Z0RYB8EYSpN48RP3YRb42_LtAm3NVHsqDxBH4A7pxYfmjGdx0DGg5h6zD2Dts82zrUSkQPRObvArcW3A0T_PmJX-8i67fSBmOI3GJM69Pb7OLCwOz8WoUvw_SQwjoIOj2mZd6-8-9Vy4j4o6bMZmD9AC2dQbHbwezH4adlZ40KyCjUvzvlUKqm51n8vCInGibJd88NiixZeyCdilAud_cmyNw
{
  "nombre":"Consultorio Z"
}
###
PUT {{DientesLimpios.API_HostAddress}}/019df07b-826c-751e-8fde-9c632fdcf34e
Content-Type: application/json
Authorization: Bearer CfDJ8KzgGGV9wRVEkndSQLLrKiB5hvQTVIcgT9E0caiZ-MHGOLmDBmVuX0wAzPKcDwgjBquG-uGshwMt4ohWkbRv-27WHfCkjwdJ1rQA_l7eAV64xBgr_J1zrdbUMUu4S8uNradzt3Kns8FqGQXJSZO_fOuVui_xtI5LjI9b8F8iEGbga-6H6fkk507EH6RO0HOLru1UL5bhH8qrrx3_DUbq5XLzRyzLtjq0npFFPEMk6Gqn3Tf1ldq4wF-ewvIIv69WOeD_fZlWnm89DEdMXlLk1ERnccNk_TXXj-5iPub_hIAw1-eyNL4fBBEAJoS965P-cVGQklchl4nwf9kbA3s0u7sDXfK7vGvBtAW33rDKqukG5cKFfrAUh2Ji_Oauy-0nTQsNB-WbJ7WeMpyKfrZDAu_DG4kO--ztDHTHFsPNoENR3b5xi5BXz4sSy5Sba86qXZ-9IsplAP29i1FrlO5Y-jyRf46o1Zh2J3JS9G2kievWbWrr103OgEnvEsEBqszsr0UITeVYUf0q7b9St3L3UODck-_TdhtKBdle_thA_Z0RYB8EYSpN48RP3YRb42_LtAm3NVHsqDxBH4A7pxYfmjGdx0DGg5h6zD2Dts82zrUSkQPRObvArcW3A0T_PmJX-8i67fSBmOI3GJM69Pb7OLCwOz8WoUvw_SQwjoIOj2mZd6-8-9Vy4j4o6bMZmD9AC2dQbHbwezH4adlZ40KyCjUvzvlUKqm51n8vCInGibJd88NiixZeyCdilAud_cmyNw
{
  "nombre":"Consultorio Z - Actualizado"
}
###

DELETE {{DientesLimpios.API_HostAddress}}/019d91f5-9453-7744-9c2a-80efd2789ae9
Accept: application/json

###